Repository depromeet/slytherin, pull requests merged in 2025-09, with the labels that each got.

#5 [Feat] API 전역 설정
  build.gradle
  src/main/java/com/bobeat/backend/global/exception/CustomException.java
  src/main/java/com/bobeat/backend/global/exception/ErrorCode.java
  src/main/java/com/bobeat/backend/global/exception/ErrorResponse.java
  src/main/java/com/bobeat/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/bobeat/backend/global/response/ApiResponse.java
  src/main/resources/application.properties
  src/test/java/com/bobeat/backend/global/api/ApiControllerIntegrationTest.java
  src/test/java/com/bobeat/backend/global/api/TestApiResponse.java
  src/test/java/com/bobeat/backend/global/api/TestController.java
  src/test/java/com/bobeat/backend/global/api/TestCustomException.java
Labels: ✨ FEAT, ❓ QUESTION, 🧩 COMMON

#11 [Common][Feat] 전체 API 엔드포인트 정의
  build.gradle
  src/main/java/com/bobeat/backend/domain/auth/controller/AuthController.java
  src/main/java/com/bobeat/backend/domain/auth/dto/request/SocialLoginRequest.java
  src/main/java/com/bobeat/backend/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/bobeat/backend/domain/member/controller/MemberController.java
  src/main/java/com/bobeat/backend/domain/member/dto/request/UpdateNicknameRequest.java
  src/main/java/com/bobeat/backend/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/bobeat/backend/domain/member/dto/response/SavedStoreDto.java
  src/main/java/com/bobeat/backend/domain/member/dto/response/SavedStoreListResponse.java
  src/main/java/com/bobeat/backend/domain/member/dto/response/UpdateNicknameResponse.java
  src/main/java/com/bobeat/backend/domain/member/entity/SocialProvider.java
  src/main/java/com/bobeat/backend/domain/onboarding/controller/OnboardingController.java
  src/main/java/com/bobeat/backend/domain/onboarding/dto/request/OnboardingAnswerDto.java
  src/main/java/com/bobeat/backend/domain/onboarding/dto/request/OnboardingRequest.java
  src/main/java/com/bobeat/backend/domain/onboarding/dto/response/OnBoardingResult.java
  src/main/java/com/bobeat/backend/domain/report/controller/ReportController.java
  src/main/java/com/bobeat/backend/domain/report/dto/request/StoreReportRequest.java
  src/main/java/com/bobeat/backend/domain/store/controller/StoreController.java
  src/main/java/com/bobeat/backend/domain/store/dto/request/EditProposalRequest.java
  src/main/java/com/bobeat/backend/domain/store/dto/request/StoreFilteringRequest.java
  src/main/java/com/bobeat/backend/domain/store/dto/request/StoreSort.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/MenuDto.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/PriceComparisonAverage.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/PriceComparisonDto.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/SeatInfoDto.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreDetailResponse.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreSearchResponse.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreSearchResultDto.java
  src/main/java/com/bobeat/backend/global/config/SwaggerConfig.java
  src/main/java/com/bobeat/backend/global/exception/ErrorResponse.java
  src/main/java/com/bobeat/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/bobeat/backend/global/response/ApiResponse.java
  src/main/java/com/bobeat/backend/global/response/CursorPageResponse.java
  src/main/java/com/bobeat/backend/global/response/CursorPaginationRequest.java
  src/test/java/com/bobeat/backend/global/api/ApiControllerIntegrationTest.java
  src/test/java/com/bobeat/backend/global/api/TestController.java
Labels: ✨ FEAT, 🧩 COMMON

#20 [Review][Feat] 리뷰 API 구현
  build.gradle
  src/main/java/com/bobeat/backend/domain/member/entity/Member.java
  src/main/java/com/bobeat/backend/domain/review/controller/ReviewController.java
  src/main/java/com/bobeat/backend/domain/review/dto/request/CreateReviewRequest.java
  src/main/java/com/bobeat/backend/domain/review/dto/request/UpdateReviewRequest.java
  src/main/java/com/bobeat/backend/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/bobeat/backend/domain/review/dto/response/StoreInfo.java
  src/main/java/com/bobeat/backend/domain/review/entity/Review.java
  src/main/java/com/bobeat/backend/domain/review/entity/ReviewKeyword.java
  src/main/java/com/bobeat/backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/bobeat/backend/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/bobeat/backend/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/bobeat/backend/domain/review/service/ReviewService.java
  src/main/java/com/bobeat/backend/domain/store/entity/HONBOB_LEVEL.java
  src/main/java/com/bobeat/backend/domain/store/repository/StoreRepository.java
  src/main/java/com/bobeat/backend/domain/store/service/StoreService.java
  src/main/java/com/bobeat/backend/global/exception/ErrorCode.java
  src/main/java/com/bobeat/backend/global/response/CursorPageResponse.java
  src/test/java/com/bobeat/backend/domain/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/bobeat/backend/domain/review/service/ReviewServiceTest.java
Labels: ✨ FEAT, ♻️ REFACTOR

#24 [Common][FIX] CI수정
  .github/workflows/ci.yml
  src/test/java/com/bobeat/backend/BackendApplicationTests.java
  src/test/java/com/bobeat/backend/domain/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/bobeat/backend/domain/store/repository/StoreRepositoryImplTest.java
  src/test/java/com/bobeat/backend/global/api/ApiControllerIntegrationTest.java
  src/test/java/com/bobeat/backend/global/db/PostgreSQLContainerExtension.java
  src/test/java/com/bobeat/backend/global/db/PostgreSQLTestContainer.java
Labels: 🛠 FIX, 🧩 COMMON

#25 [Security][Feature] JWT 인증 시스템 및 소셜 로그인 구현
  build.gradle
  src/main/java/com/bobeat/backend/domain/auth/controller/AuthController.java
  src/main/java/com/bobeat/backend/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/bobeat/backend/domain/member/controller/MemberController.java
  src/main/java/com/bobeat/backend/domain/member/controller/OnboardingController.java
  src/main/java/com/bobeat/backend/domain/member/entity/Member.java
  src/main/java/com/bobeat/backend/domain/member/entity/MemberRole.java
  src/main/java/com/bobeat/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bobeat/backend/domain/member/service/OnboardingService.java
  src/main/java/com/bobeat/backend/domain/review/controller/ReviewController.java
  src/main/java/com/bobeat/backend/domain/security/auth/api/JwtTokenController.java
  src/main/java/com/bobeat/backend/domain/security/auth/dao/RefreshTokenRepository.java
  src/main/java/com/bobeat/backend/domain/security/auth/domain/RefreshToken.java
  src/main/java/com/bobeat/backend/domain/security/auth/dto/AuthResponse.java
  src/main/java/com/bobeat/backend/domain/security/auth/dto/TokenClaims.java
  src/main/java/com/bobeat/backend/domain/security/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/bobeat/backend/domain/security/auth/service/AuthService.java
  src/main/java/com/bobeat/backend/domain/security/auth/service/JwtService.java
  src/main/java/com/bobeat/backend/domain/security/oauth/OauthController.java
  src/main/java/com/bobeat/backend/domain/security/oauth/OauthService.java
  src/main/java/com/bobeat/backend/domain/security/oauth/dto/GoogleUserInfo.java
  src/main/java/com/bobeat/backend/domain/security/oauth/dto/KakaoUserInfo.java
  src/main/java/com/bobeat/backend/domain/security/oauth/dto/OAuth2UserInfo.java
  src/main/java/com/bobeat/backend/domain/security/oauth/dto/request/SocialLoginRequest.java
  src/main/java/com/bobeat/backend/domain/security/oauth/service/GoogleService.java
  src/main/java/com/bobeat/backend/domain/security/oauth/service/KakaoService.java
  src/main/java/com/bobeat/backend/domain/security/oauth/service/OAuth2Factory.java
  src/main/java/com/bobeat/backend/domain/security/oauth/service/OAuth2Service.java
  src/main/java/com/bobeat/backend/global/config/SecurityConfig.java
  src/main/java/com/bobeat/backend/global/config/WebClientConfig.java
  src/main/java/com/bobeat/backend/global/exception/ErrorCode.java
  src/main/java/com/bobeat/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/bobeat/backend/global/response/ApiResponse.java
  src/test/java/com/bobeat/backend/domain/security/SecurityIntegrationTest.java
  src/test/java/com/bobeat/backend/global/api/ApiControllerIntegrationTest.java
  src/test/resources/application-test.yml
Labels: ✨ FEAT, ♻️ REFACTOR, 👤 USER, 🧩 COMMON

#29 [Food][Refactor] repository에서 커서 리스폰스 안하도록 변경(storeservice에게 위임)
  src/main/java/com/bobeat/backend/domain/store/controller/StoreController.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreSearchResultDto.java
  src/main/java/com/bobeat/backend/domain/store/entity/MemberSavedStore.java
  src/main/java/com/bobeat/backend/domain/store/entity/SeatOption.java
  src/main/java/com/bobeat/backend/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/bobeat/backend/domain/store/repository/StoreRepositoryImpl.java
  src/main/java/com/bobeat/backend/domain/store/service/StoreService.java
  src/test/java/com/bobeat/backend/domain/store/repository/StoreRepositoryImplTest.java
  src/test/resources/application-test.yml
Labels: ♻️ REFACTOR, 🍔 FOOD

#31 [Common][Fix] CD 수정
  infra/docker/docker-compose.yml
  infra/script/deploy.sh
Labels: 🐛 BUG, 🧩 COMMON

#36 [Store][Feat] 어드민 용 가게 벌크 생성 API
  src/main/java/com/bobeat/backend/domain/member/entity/Member.java
  src/main/java/com/bobeat/backend/domain/store/controller/AdminStoreController.java
  src/main/java/com/bobeat/backend/domain/store/dto/request/StoreCreateRequest.java
  src/main/java/com/bobeat/backend/domain/store/entity/Store.java
  src/main/java/com/bobeat/backend/domain/store/entity/StoreType.java
  src/main/java/com/bobeat/backend/domain/store/repository/PrimaryCategoryRepository.java
  src/main/java/com/bobeat/backend/domain/store/repository/SecondaryCategoryRepository.java
  src/main/java/com/bobeat/backend/domain/store/service/StoreService.java
  src/main/java/com/bobeat/backend/domain/store/vo/Categories.java
  src/main/java/com/bobeat/backend/global/config/GeometryConfig.java
  src/main/java/com/bobeat/backend/global/exception/ErrorCode.java
Labels: ✨ FEAT

#39 [Common][Feat] 디스코드 에러 알림 구현
  .github/workflows/ci.yml
  src/main/java/com/bobeat/backend/global/config/DiscordWebhookConfig.java
  src/main/java/com/bobeat/backend/global/config/ErrorNotificationConfig.java
  src/main/java/com/bobeat/backend/global/error_notification/DiscordErrorNotificationDto.java
  src/main/java/com/bobeat/backend/global/error_notification/ErrorNotificationDto.java
  src/main/java/com/bobeat/backend/global/error_notification/ErrorNotificationService.java
  src/main/java/com/bobeat/backend/global/error_notification/SenderToDiscord.java
  src/main/java/com/bobeat/backend/global/exception/GlobalExceptionHandler.java
  src/test/java/com/bobeat/backend/domain/store/repository/StoreRepositoryImplTest.java
Labels: ✨ FEAT, 🧩 COMMON

#40 [JWT][Feat] 리프레쉬 토큰 유효기간 로깅 추가
  src/main/java/com/bobeat/backend/domain/security/auth/api/TempJWTController.java
  src/main/java/com/bobeat/backend/domain/security/auth/service/AuthService.java
  src/main/java/com/bobeat/backend/domain/security/auth/service/JwtService.java
Labels: ♻️ REFACTOR, 🧩 COMMON

#35 [Food][Fix] store api 쿼리 별 함수 분리 및 요청 파라미터 최신화
  src/main/java/com/bobeat/backend/domain/store/controller/StoreController.java
  src/main/java/com/bobeat/backend/domain/store/dto/request/StoreFilteringRequest.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreDetailResponse.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreSearchResponse.java
  src/main/java/com/bobeat/backend/domain/store/dto/response/StoreSearchResultDto.java
  src/main/java/com/bobeat/backend/domain/store/entity/Store.java
  src/main/java/com/bobeat/backend/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/bobeat/backend/domain/store/repository/StoreRepositoryImpl.java
  src/main/java/com/bobeat/backend/domain/store/service/StoreService.java
  src/main/java/com/bobeat/backend/global/exception/ErrorCode.java
  src/main/java/com/bobeat/backend/global/response/CursorPageResponse.java
  src/main/java/com/bobeat/backend/global/util/KeysetCursor.java
Labels: 🛠 FIX, ♻️ REFACTOR, 🍔 FOOD

#51 [Admin][Fix] admin store 쓰기 작업 실패 수정
  build.gradle
  src/main/java/com/bobeat/backend/domain/store/dto/request/StoreCreateRequest.java
Labels: 🐛 BUG, 🛠 FIX, 🛠️ ADMIN

#52 [Food][Fix] 리뷰 조회 시 레벨까지 받아올 수 있도록 수정
  src/main/java/com/bobeat/backend/domain/member/entity/Member.java
  src/main/java/com/bobeat/backend/domain/member/entity/MemberOnboardingProfile.java
  src/main/java/com/bobeat/backend/domain/member/service/MemberService.java
  src/main/java/com/bobeat/backend/domain/member/service/OnboardingService.java
  src/main/java/com/bobeat/backend/domain/review/dto/response/ReviewResponse.java
  src/test/java/com/bobeat/backend/domain/member/entity/MemberOnboardingProfileTest.java
  src/test/java/com/bobeat/backend/domain/review/service/ReviewServiceTest.java
Labels: ✨ FEAT, 🛠 FIX, 🍔 FOOD
